services:
  - type: web
    name: btrate
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DEMO_MODE
        value: "true"
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: "10000"
